### ISSUE TITLE
We should have a way to disagree with vote requests, and move them to the graveyard if enough people agree

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/SO-Close-Vote-Reviewers.github.io#25]
In the close vote queue, 5 people are needed to close a question, but only 3 are needed to say "looks good", which will remove that post from the queue.

Right now, we don't move close vote requests (and others) to the graveyard until they are "completed", which means closed or deleted. That means our transcript fills up with "uncompleted" vote requests because people don't agree with them.

I think we should have some method to let chat members give feedback on a vote request to say that it looks good - either because they think the vote request is incorrect or the post has been altered to make it ok. At this point the RO's archiver userscript will move any of these requests that gather (subject to argument) 2 or 3 "looks good" feedbacks.

This way, the graveyard isn't _just_ a list of burned questions.

**Comment by Tiny-Giant** [comment]
Right now any request older than 3 days is moved regadless of its state

**Comment by gunr2171** [comment]
I was not aware of that / forgot about it. That's a good way of dealing with requests that are not acted on.

Someone can reopen if that's not a good method and we can take this to a meeting.

**Comment by gunr2171** [comment]
Reopening this because a few people, myself included, would like a more formal way of tracking and managing these.

**Comment by magisch** [comment]
I'd also like a way to do that. It should be publicly visible too. Would do a great deal for our public perception (right now lots of people, whether they're right about it or not, think that we take member's word for a close request. A formal way to disagree would alleviate that concern significantly).

**Comment by Tyler-H** [comment]
It's going to be difficult to do this because of the nature of our gathering place; a chat room with a timed limit on editing posts, with no way of assigning any tags or meta data to a given chat message. Ideally this would be a feature added to chat natively where we could assign a 'vote' of some kind inline, but it may have to be done via user script (and thus the next problem will be forcing engagement from SOCVR members)

**Comment by ghost** [comment]
We could bring forward a quicker time frame for automatically removing requests. 24 hours should be enough. There's enough active close voters in the room to close a post within 24 hours. This would solve the issue of trying to gain the formal vote of 3 on a request and the noise it may create in chat.
A native vote as Tyler suggested would be the optimal way to deal with this otherwise, but takes more work.

**Comment by Tunaki** [comment]
[Bookmark](http://chat.stackoverflow.com/rooms/108179/conversation/2017-january-topic-3)

Yes, the functionality is wanted. Possible implementation: Have a formatted response like `:<message ID> Disagree. <reasoning>`. The graveyard script should also archive disagreements. Tracking through editing is not always a practical solution.
