### ISSUE TITLE
Should we remove the room's events from the calendar?

### ISSUE THREAD

**Issue by Cerbrus** [SO-Close-Vote-Reviewers/SO-Close-Vote-Reviewers.github.io#32]
There are 3 events each week on the calendar to "Clear the CVQ".

Are those events really necessary? Does anyone even _do_ something with these events?

That's 3 banners I have to close at 2 different machines each week. As trivial as that may seem, the notifications get a little annoying.

**Comment by Tiny-Giant** [comment]
As this banner shows up for all chat users, it helps to draw in new members. Not to mention that it gets a bunch of users reviewing the same tags in the close vote queue at the same time.

**Comment by Cerbrus** [comment]
@Tiny-Giant when was the last time anyone even mentioned or acted on the event in the room?

I'm all for the idea behind the event. But the notifications are annoying, especially if they're not acted on.

**Comment by Tiny-Giant** [comment]
Recently, closey has been broken. Closey was part of the main draw about the events. It provides feedback and tracks your progress which is engaging when performing an otherwise overly mundane task. I try to start the @5UTC event when I can even though closey is down, but I can't always make it.

That said, I'm not opposed to discussing this, I'm just of the opinion that they should stay.

**Comment by Tyler-H** [comment]
@Tiny-Giant  That's a great segue into fixing Closey :-)

**Comment by Tunaki** [comment]
[Bookmark](http://chat.stackoverflow.com/rooms/108179/conversation/2017-january-topic-4)

Our tooling and mindsets have evolved, the CV queue and the events hardly. Events can bind us as a room and be used as special moments to share moderation. We have to find a better way to handle them, a way to engage more people into them. Until then, have a pause and we'll disable the events.
